- name: Cleanup kubernetes folder
  file:
    state: absent
    path: "kubernetes"
- file: path=kubernetes state=directory

- name: Set the cluster to the specified one
  command: "kubectl config use-context {{ cluster_context }}"

- name: prepare templates
  template:
    src: "{{ item }}"
    dest: kubernetes/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/*.j2

- name: Configuring database authentication
  include_tasks: postgres.yml
  when: use_postgresql_auth == true

- name: Configure file-based authentication
  include_tasks: file_based_auth.yml
  when: use_postgresql_auth == false

- name: Deploy cluster
  command: "kubectl apply -f kubernetes/vernemq-cluster.yaml -n {{ cluster_namespace }}"

- name: Wait for a minute so the loadbalancer can be started
  wait_for: timeout=60
