- name: Destroy stateful set and pods
  command: "kubectl delete statefulset,po -l app=vernemq --namespace={{ cluster_namespace }}"

- name: Destroy secrets
  command: "kubectl delete secrets vernemq-passwd --namespace={{ cluster_namespace }}"

- name: Destroy configmap
  command: "kubectl delete configmap vernemq-config --namespace={{ cluster_namespace }}"

- name: Destroy service vernemq
  command: "kubectl delete service vernemq --namespace={{ cluster_namespace }}"

- name: Destroy service mqtts
  command: "kubectl delete service mqtts --namespace={{ cluster_namespace }}"