- name: Destroy stateful set and pods
  command: "kubectl delete statefulset,po -l app=vernemq --namespace={{ cluster_namespace }}"

- name: Wait for grace period
  pause:
    seconds: "{{ grace_period.stdout_lines.0 }}"

- name: Destroy secrets
  command: "kubectl delete secrets vernemq-passwd --namespace={{ cluster_namespace }}"

- name: Destroy service
  command: "kubectl delete service vernemq --namespace={{ cluster_namespace }}"

- name: Destroy service
  command: "kubectl delete service mqtts --namespace={{ cluster_namespace }}"