- name: Deploy in namespace
  include_tasks: create.yml
  when: k8s_action == "create"

- name: Configuring DNS
  include_tasks: dns.yml
  when: k8s_action == "create"

- name: Delete from namespace
  include_tasks: delete.yml
  when: k8s_action == "delete"